// Generated by CoffeeScript 1.7.1
(function() {
  var AQUESTALKPI, exec, main, talk;

  AQUESTALKPI = "/home/pi/aquestalkpi/AquesTalkPi";

  exec = require('child_process').exec;

  main = function() {
    return setInterval((function() {
      var date;
      date = new Date();
      if (date.getHours() === 5) {
        date.getMinutes() === 0;
      }
      talk("しゅうぎょうじこくになりました。　かえりましょう。");
      return talk("げんざいのじこくは、" + (date.getHours()) + "じ、" + (date.getMinutes()) + "ふん、です。");
    }), 60 * 1000);
  };

  talk = (function() {
    var talking;
    talking = false;
    return function(text, cb) {
      if (cb == null) {
        cb = function() {};
      }
      if (talking) {
        return cb(false);
      }
      talking = true;
      return exec("" + AQUESTALKPI + " \"" + text + "\" | aplay", function(err, stdout, stderr) {
        talking = false;
        if (!err) {
          return cb();
        } else {
          console.log(err);
          console.log(err.code);
          return console.log(err.signal);
        }
      });
    };
  })();

  main();

}).call(this);
